CREATE TABLE IF NOT EXISTS departments (
    ID BIGINT IDENTITY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS employees (
    ID BIGINT IDENTITY,
    DEPARTMENT_ID BIGINT NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PATRONYMIC VARCHAR(255) NOT NULL,
    DATE_OF_BIRTHDAY TIMESTAMP NOT NULL,
    SALARY BIGINT NOT NULL
);